# Generated by Django 4.0.2 on 2022-08-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('pronoun', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=1000)),
            ],
        ),
    ]
