# Generated by Django 4.0.2 on 2022-09-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='users',
            new_name='user',
        ),
    ]
